name: Build ZMK

on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - "boards/**"
      - "zephyr/**"
      - "build.yaml"
  pull_request:
    paths:
      - "config/**"
      - "boards/**"
      - "zephyr/**"
      - "build.yaml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
